### ISSUE TITLE
Looks like the SOQL generation is incorrect

### ISSUE THREAD

**Issue by bobalicious** [wimvelzeboer/fflib-apex-extensions#19]
Quick test suggests that the {0} {2} {3} in the Soql String.format methods is incorrect.

E.g. getting `Id '00axxxxxxxxx' {3}` when formatting a call to `inSet( new Set<Id>{ '00axxxxxxxxx' } )`

Suspect it should be {0} {1} {2}

Change to the format does not break any tests, suggesting a gap in the unit testing

Example in code (not limited to one instance):
https://github.com/wimvelzeboer/fflib-apex-extensions/blob/910219dd8cfee09f12eabba64de657a4765010d2/sfdx-source/apex-extensions/main/default/classes/criteria/fflib_Criteria.cls#L855

**Comment by wimvelzeboer** [comment]
@bobalicious Thanks for pointing that one out! 
Indeed it seems that the unit-test coverage is not enough at the point.
I have fixed the bug!
Will have to see if I can check the unit-test coverage soon, or if you feel up to it, then you can also raise a PR.

**Comment by wimvelzeboer** [comment]
@bobalicious I have added extra unit-test coverage, particularly for the SOQL generation. The total unit-test coverage for fflib_Criteria has now been increased to 80%.
